### ISSUE TITLE
Creating Strong random Passwords

### ISSUE THREAD

**Issue by AMAN-BAGADIYA** [avinashkranjan/Amazing-Python-Scripts#1424]
Hey @avinashkranjan, I am Aman Bagadiya. Please assign this issue to me. Thank You!

**Comment by AMAN-BAGADIYA** [comment]
Yes, I have followed the guidelines properly! Please assign it to me.

**Comment by rahulkothuri** [comment]
Hello! @avinashkranjan I'll work on this issue fast. Assign me this issue as a contributor in GSSOC'23

**Comment by 1e9abhi1e10** [comment]
Dear @AMAN-BAGADIYA, The code for this issue is already present in the repo. Kindly come with another issue!

Check here:
[Password-Generator]( https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Password-Generator)
[Random Password Generator](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Random%20Password%20Generator)
