### ISSUE TITLE
SMS Automation

### ISSUE THREAD

**Issue by slashharsh** [avinashkranjan/Amazing-Python-Scripts#279]
# Aim

- The Aim is to send SMS (Short message service) to multiple people using python.

# Details

- It will be able to send message to multiple people by one script
- Scheduler will be there to send messages (greetings etc.) to send SMS at a particular time.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @slashharsh

**Comment by slashharsh** [comment]
Thanks!

**Comment by pritamp17** [comment]
@avinashkranjan sir I would like to work on this script using Nodejs, could you please assign me this?

**Comment by avinashkranjan** [comment]
> @avinashkranjan sir I would like to work on this script using Nodejs, could you please assign me this?

No, Script is supposed to be in Python only..and it's already assigned to someone else..

**Comment by pritamp17** [comment]
ok

**Comment by TanviDeore** [comment]
I would like to work on this issue as a GSSoC'21 participant.

**Comment by avinashkranjan** [comment]
Assigned to you @TanviDeore

**Comment by kaustubhgupta** [comment]
@TanviDeore Updates on this?

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me?

**Comment by kaustubhgupta** [comment]
@prathimacode-hub assigned to you

**Comment by prathimacode-hub** [comment]
Thankyou for assigning it to me. What's the best medium to communicate? @kaustubhgupta @avinashkranjan

**Comment by kaustubhgupta** [comment]
> Thankyou for assigning it to me. What's the best medium to communicate? @kaustubhgupta @avinashkranjan

This issues, discussions tab where you can create your own topic or discord project channel. (P.S: I am most active over GitHub)

**Comment by prathimacode-hub** [comment]
I'm new to opensource and github. I have forked the repository. Can you help with any reference of how to successfully clone and merge PR? @kaustubhgupta

**Comment by kaustubhgupta** [comment]
Read the contribution guide of this repo. It's actually well written. https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md

**Comment by kaustubhgupta** [comment]
@prathimacode-hub updates?

**Comment by prathimacode-hub** [comment]
I'm working on it. I'll updatet by today evening. @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@prathimacode-hub Final update?

**Comment by prathimacode-hub** [comment]
Yes, It's in final stage. For sms automation, I've used FAST2SMS API and created a GUI to send messages promptly to any number of the user's choice. Currently, I've power issues at my place. Sorry for the delay. I'll send as early as possible. @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@prathimacode-hub Oh no issues, I only need to know that you are working on this and the progress of the script.

**Comment by kaustubhgupta** [comment]
@prathimacode-hub ?

**Comment by prathimacode-hub** [comment]
Yes, I am working on this. I'm done with the code. Got an issue on library which i'm looking through it. @kaustubhgupta

**Comment by kaustubhgupta** [comment]
okay

**Comment by kaustubhgupta** [comment]
@prathimacode-hub You need to make the PR today only else this will be assigned to someone else

**Comment by prathimacode-hub** [comment]
Ok @kaustubhgupta

**Comment by prathimacode-hub** [comment]
I've completed the project. I'm getting difficulty in doing PR. Do we have to create a PR or merge a PR? Can I create a PR from here or through my profile? @kaustubhgupta

**Comment by kaustubhgupta** [comment]
Check out the contribution guide to get a detailed instruction for this

**Comment by kaustubhgupta** [comment]
@prathimacode-hub?

**Comment by prathimacode-hub** [comment]
You can assign it to someone else. I'll learn github first. Then i will get issues assigned to me. Sorry for the delay I'm causing. @kaustubhgupta

**Comment by kaustubhgupta** [comment]
> You can assign it to someone else. I'll learn github first. Then i will get issues assigned to me. Sorry for the delay I'm causing. @kaustubhgupta

No, if you have completed the code and then facing issues to make PR then I can help you from the start. We are here to get you started with this only. Let me know your decision: you want to learn how to push your code to our repo or drop this assignment?

**Comment by prathimacode-hub** [comment]
I want to learn to push the code. Yes.

**Comment by kaustubhgupta** [comment]
## Overview of the process
Whenever you want to work on any issue in any repo, after forking the repo, make a clone of that forked repo into your local system. Then create a git branch on your local system so that if you're assigned multiple issues, then you can work on them separately. Then push your changes to your forked repo and then create the PR.

## Doing this practically
- I am assuming that you installed Git on your system. If not, then head over to this link: https://git-scm.com/
- Now open your terminal (cmd in win,) and type git. If you get some help commands that means Git is set up in your system. Now set up the git parameters:
```bash
git config --global user.name "<your user name>"
git config --global user.email <your email>
```
- Now navigate to the folder where you want to set up the project.
- (Assuming you have forked it in GitHub)Open the terminal in that directory and type git clone https://github.com/<your user name here>/Amazing-Python-Scripts.git
- Navigate to the new directory created Amazing-Python-Scripts in the terminal and type the following commands in order:
```bash
git remote add upstream https://github.com/avinashkranjan/Amazing-Python-Scripts
git checkout -b <name of new branch>
``` 
This will set up the data flow to update your local copy of code with PA's code and the next command created a local branch.

- Now, put your code folder (Sms-Automation in your case) in the new directory created Amazing-Python-Scripts. 
- Now:
```bash
git pull upstream
git add .
git commit -m "Adding SMS automation"
git push origin
```
This will add your code to your forked repo in GitHub. To make the PR:
- Go to the repo in Github and you will be prompted to create a PR
- Click create and at the bottom create.

This is how you do it. If you face any issues, you can ping me here

**Comment by kaustubhgupta** [comment]
@prathimacode-hub After this much effort, you didn't bother to try this and therefore, I have no choice but to unassign this issue

**Comment by prathimacode-hub** [comment]
@kaustubhgupta I had power issues at my place. Due to which I wasn't available here.

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this issue??

**Comment by Lakhankumawat** [comment]
- I can actively complete it within a week @kaustubhgupta sir without any delays ,you can assign me .

**Comment by kaustubhgupta** [comment]
@Lakhankumawat As @Amit366 has commented earlier (which for some reason I didn't saw the message earlier), this issue will be assigned to @Amit366

**Comment by Lakhankumawat** [comment]
O okay First Come First Serve 😅

**Comment by Amit366** [comment]
@santushtisharma10 for this can I use twilio?? But in twilio it says the number is invalid for sending messages.

**Comment by santushtisharma10** [comment]
@Amit366 make sure that the number is in E164 format.

**Comment by Amit366** [comment]
Ok
