### ISSUE TITLE
Enhancing Data Visualization Scripts

### ISSUE THREAD

**Issue by ELITA04** [avinashkranjan/Amazing-Python-Scripts#515]
Hello, I am a participant of GSSOC'21 and I want to work on the enhancement and refactoring of  Data Visualizations scripts.

I want to use Plotly to create more visually appealing and interactive charts. This would  even provide  better images of the output for the visualization on the README.md

Please assign this issue to me. Thank you

_Updates_: The script which will be updated is: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Data-Visualization

**Comment by kaustubhgupta** [comment]
@ELITA04 what visualization would you fix in this issue? If there are more, then we can split this among multiple people.

**Comment by ELITA04** [comment]
Hi, I want to use Plotly to create much more interactive charts.
An example of Plotly's graphs
![issue1](https://user-images.githubusercontent.com/46682884/111019676-e7d2ca00-83e6-11eb-8ed5-e972d56cb93a.jpg)

I also wanted to add other visualizations like bubble charts, heat maps, dot plots, and horizontal bar charts

**Comment by kaustubhgupta** [comment]
@ELITA04 I am aware of Plotly and have been using it for a year. I want to where you want to apply these plots? In which script?

**Comment by ELITA04** [comment]
Here, https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Data-Visualization

I am sorry I misunderstood your question

**Comment by kaustubhgupta** [comment]
@ELITA04 No worries, Now I understood your point. Sur go ahead! As I saw the scripts now, the data for which plots were made is hardcoded. I would request you to use numpy to generate random data (with seed so that you can save the best visualization) and play with important attributes of the plot to make it clean and appealing. Use theme="plotly_dark" for all the plots!

I have renamed the issue and description.
